[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "biasfish"
version = "0.1.0"
description = "A CLI chess engine with biased evaluation"
authors = [{name="RealPhonki"}]
dependencies = [
    "python-chess"
]

[project.scripts]
biasfish = "biasfish.main:main"

[tool.pylint.messages_control]
disable = [
    "trailing-whitespace",
    "missing-module-docstring",
    "missing-final-newline",
    "wildcard-import",
    "import-error",
    "invalid-name"
]